import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/app.context";
import NextAuthWrapper from "@/context/next.auth.wrapper";
import ContextFloatingBtn from "@/components/layout/context.floating.btn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppContextProvider>
          <NextAuthWrapper>
            {children}
            <ContextFloatingBtn></ContextFloatingBtn>
          </NextAuthWrapper>
        </AppContextProvider>
      </body>
    </html>
  );
}
